const DATA={
 aircraft:{
  falcon:{name:'FALCON',base:'직선 캐논',weapon:'straight',path:'assets/aircraft/pk-a01_falcon/pk-a01_falcon',color:'#2e87ff',unlocked:true},
  vulcan:{name:'VULCAN',base:'산탄 캐논',weapon:'spread',path:'assets/aircraft/pk-b01_vulcan/pk-b01_vulcan',color:'#ff5a1f',unlocked:true}
 },
 weapons:{straight:'직선',spread:'산탄',laser:'레이저',chain:'체인',shield:'실드'},
 research:[['Gold Mining','골드 획득 +2%'],['Auto Fire','공격속도 +2%'],['EXP Gain','경험치 +3%']],
 missions:[
  {id:'kill30',name:'적 30기 처치',gold:500,rp:20,goal:30,type:'kill'},
  {id:'level3',name:'레벨업 3회 사용',gold:700,rp:25,goal:3,type:'level'},
  {id:'play1',name:'게임 1회 플레이',gold:300,rp:10,goal:1,type:'play'}
 ]
};
const $=s=>document.querySelector(s);const saveKey='projectK_v100';
let state=load();function load(){let d={gold:1000,rp:100,pilotLv:1,selected:'falcon',missions:{},stats:{kill:0,level:0,play:0}};try{return {...d,...JSON.parse(localStorage.getItem(saveKey)||'{}')}}catch(e){return d}}
function save(){localStorage.setItem(saveKey,JSON.stringify(state))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1300)}
function renderLobby(){const a=DATA.aircraft[state.selected];$('#pilotLv').textContent=state.pilotLv;$('#goldView').textContent=state.gold;$('#rpView').textContent=state.rp;$('#shipName').textContent=a.name;$('#baseWeapon').textContent=a.base;$('#lobbyShip').src=`${a.path}_lv5.svg`;$('#researchList').innerHTML=DATA.research.map((r,i)=>`<div class="mini-card"><b>${r[0]}</b><br>${r[1]}<br>Lv.${i+1}</div>`).join('');$('#aircraftList').innerHTML=Object.entries(DATA.aircraft).map(([id,x])=>`<button class="mini-card" onclick="selectAircraft('${id}')"><img src="${x.path}_icon.svg" style="width:48px;height:48px;object-fit:contain;vertical-align:middle"> <b>${x.name}</b><br>${state.selected===id?'선택 중':'선택'}</button>`).join('');renderMissions()}
window.selectAircraft=id=>{state.selected=id;save();renderLobby()};
function renderMissions(){const box=$('#missionList');box.innerHTML=DATA.missions.map(m=>{let p=Math.min(m.goal,state.stats[m.type]||0),claimed=state.missions[m.id];return `<div class="mission-row"><div><b>${m.name}</b><br><span style="color:#64ff87">${p}/${m.goal}</span> 보상 G ${m.gold} / RP ${m.rp}</div><button class="claim" ${p<m.goal||claimed?'disabled':''} onclick="claimMission('${m.id}')">${claimed?'완료':'수령'}</button></div>`}).join('')}
window.claimMission=id=>{const m=DATA.missions.find(x=>x.id===id);if(!m||state.missions[id]||(state.stats[m.type]||0)<m.goal)return;state.gold+=m.gold;state.rp+=m.rp;state.missions[id]=true;save();renderLobby();Object.values(DATA.aircraft).forEach(a=>{for(let i=1;i<=5;i++)loadImg(`${a.path}_lv${i}.svg`);loadImg(`${a.path}_icon.svg`)});toast(`보상 획득 G ${m.gold} / RP ${m.rp}`)};
$('#missionIcon').onclick=()=>{$('#missionModal').classList.add('show');renderMissions()};$('#closeMission').onclick=()=>$('#missionModal').classList.remove('show');
renderLobby();Object.values(DATA.aircraft).forEach(a=>{for(let i=1;i<=5;i++)loadImg(`${a.path}_lv${i}.svg`);loadImg(`${a.path}_icon.svg`)});

const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d');let W=0,H=0;function resize(){const app=document.getElementById('app');const rect=app.getBoundingClientRect();let cw=rect.width||window.innerWidth||420;let ch=rect.height||window.innerHeight||640;canvas.style.width=cw+'px';canvas.style.height=ch+'px';const dpr=window.devicePixelRatio||1;canvas.width=Math.floor(cw*dpr);canvas.height=Math.floor(ch*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);W=cw;H=ch}window.addEventListener('resize',resize);window.addEventListener('orientationchange',()=>setTimeout(resize,120));resize();
let imgs={};function loadImg(src){if(imgs[src])return imgs[src];let im=new Image();im.src=src;imgs[src]=im;return im}
let game=null;
function startGame(){const a=DATA.aircraft[state.selected];$('#lobby').classList.remove('active');$('#game').classList.add('active');resize();requestAnimationFrame(()=>{resize();game={running:true,time:0,stage:1,kills:0,need:18,gold:0,xp:0,nextXp:100,pending:0,usedLevels:0,speed:1,slow:false,player:{x:W/2,y:H-120,tx:W/2,ty:H-120,hp:100,max:100,lv:1,ship:a,shot:0},bullets:[],enemies:[],effects:[],lastSpawn:0};state.stats.play=(state.stats.play||0)+1;save();updateWeapons();updateLevelCore();});}
$('#startBtn').onclick=startGame;
function endGame(){state.gold+=game.gold;save();renderLobby();Object.values(DATA.aircraft).forEach(a=>{for(let i=1;i<=5;i++)loadImg(`${a.path}_lv${i}.svg`);loadImg(`${a.path}_icon.svg`)});$('#game').classList.remove('active');$('#lobby').classList.add('active');toast(`획득 Gold ${game.gold}`);game=null}
$('#pauseBtn').onclick=endGame;
function setTarget(e){if(!game)return;let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;game.player.tx=p.clientX-r.left;game.player.ty=p.clientY-r.top-30;e.preventDefault?.()}
canvas.addEventListener('mousemove',setTarget);canvas.addEventListener('touchmove',setTarget,{passive:false});canvas.addEventListener('touchstart',setTarget,{passive:false});
$('#speedBtn').onclick=()=>{if(!game)return;game.speed=game.speed===1?2:game.speed===2?3:1;$('#speedBtn').innerHTML=`⏩<br>x${game.speed}`;$('#speedBtn').className=`speed-btn x${game.speed}`;toast(`SPEED x${game.speed}`)};
$('#levelCore').onclick=()=>{if(!game||game.pending<=0)return;openLevel()};$('#closeLevel').onclick=()=>closeLevel();
function openLevel(){game.slow=true;$('#levelModal').classList.add('show');makeCards()}
function closeLevel(){$('#levelModal').classList.remove('show');if(game)game.slow=false}
function makeCards(){let cards=[['laser','레이저 획득/강화','얇은 관통 레이저를 추가합니다.'],['chain','체인 획득/강화','처치 시 주변 적에게 연쇄 피해.'],['heal','긴급 수리','HP를 35% 회복합니다.']];$('#cardList').innerHTML=cards.map(c=>`<div class="card ${c[0]==='laser'?'evo':''}" onclick="chooseCard('${c[0]}')"><div class="card-title">${c[1]}</div><div class="card-desc">${c[2]}</div></div>`).join('')}
window.chooseCard=id=>{if(!game)return;if(id==='heal')game.player.hp=Math.min(game.player.max,game.player.hp+35);else game[id]=(game[id]||0)+1;game.pending--;game.usedLevels++;state.stats.level=(state.stats.level||0)+1;save();updateWeapons();closeLevel();updateLevelCore();};
function updateWeapons(){if(!game)return;let p=game.player;let items=[`${p.ship.base} Lv.${p.lv}`];if(game.laser)items.push(`레이저 Lv.${game.laser}`);if(game.chain)items.push(`체인 Lv.${game.chain}`);$('#weaponPanel').innerHTML=items.map(t=>`<div class="weapon-item">${t}</div>`).join('')}
function updateLevelCore(){if(!game)return;const b=$('#levelCore');if(game.pending>0){b.classList.add('show');b.querySelector('b').textContent=game.pending}else b.classList.remove('show')}
function spawn(){let type=Math.random();let hp=type>.82?38:18;game.enemies.push({x:20+Math.random()*(W-40),y:-30,vx:(Math.random()-.5)*.5,vy:1.2+Math.random()*.8,hp,max:hp,r:type>.82?22:15,kind:type>.82?'bomber':'normal',shot:0})}
function shoot(dt){let p=game.player;p.shot-=dt;if(p.shot>0)return;p.shot=260/(game.speed||1);let base=p.ship.weapon;if(base==='spread'){[-.35,0,.35].forEach(a=>game.bullets.push({x:p.x,y:p.y-34,vx:Math.sin(a)*4,vy:-7,damage:12,color:'#ff5a1f',r:4}))}else{let count=Math.min(3,p.lv);for(let i=0;i<count;i++)game.bullets.push({x:p.x+(i-(count-1)/2)*13,y:p.y-34,vx:0,vy:-8,damage:14,color:'#63c7ff',r:4})}if(game.laser){game.bullets.push({x:p.x,y:p.y-52,vx:0,vy:-999,damage:3+game.laser*2,color:'#70fff2',laser:true,life:95,width:8+game.laser*2})}}
function step(now){requestAnimationFrame(step);if(!game){drawIdle();return}let dt=Math.min(32,now-(game.time||now));game.time=now;let scale=game.speed*(game.slow?0.2:1);update(dt*scale);draw()}
function update(dt){let p=game.player;let f=Math.max(0.1,dt/16.67);p.x+=(p.tx-p.x)*Math.min(1,.11*f);p.y+=(p.ty-p.y)*Math.min(1,.11*f);p.x=Math.max(30,Math.min(W-30,p.x));p.y=Math.max(80,Math.min(H-40,p.y));game.lastSpawn-=dt;if(game.lastSpawn<=0){spawn();game.lastSpawn=650}shoot(dt);game.bullets.forEach(b=>{if(!b.laser){b.x+=b.vx*f;b.y+=b.vy*f}else b.life-=dt});game.bullets=game.bullets.filter(b=>b.y>-80&&b.life!==undefined?b.life>0:b.y>-80);game.enemies.forEach(e=>{e.x+=e.vx*f;e.y+=e.vy*f;if(Math.hypot(e.x-p.x,e.y-p.y)<e.r+20){p.hp-=.35*f;if(p.hp<=0)endGame()}});for(let e of game.enemies){for(let b of game.bullets){let hit=b.laser?(Math.abs(e.x-b.x)<b.width&&e.y<p.y):(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r);if(hit){e.hp-=b.damage;if(!b.laser)b.y=-999;if(Math.random()<.2)game.effects.push({x:e.x,y:e.y,t:'+G',life:40,color:'#ffd15a'})}}}game.enemies=game.enemies.filter(e=>{if(e.hp<=0){game.kills++;state.stats.kill=(state.stats.kill||0)+1;game.gold+=e.kind==='bomber'?8:3;game.xp+=e.kind==='bomber'?32:18;game.effects.push({x:e.x,y:e.y,t:`+${e.kind==='bomber'?8:3}G`,life:45,color:'#ffd15a'});if(game.chain)game.enemies.forEach(o=>{if(Math.hypot(o.x-e.x,o.y-e.y)<90)o.hp-=8*game.chain});return false}return e.y<H+50});if(game.xp>=game.nextXp){game.xp-=game.nextXp;game.nextXp=Math.floor(game.nextXp*1.45+40);game.pending++;p.lv=Math.min(5,p.lv+1);updateLevelCore();updateWeapons()}if(game.kills>=game.need){game.stage++;game.kills=0;game.need=Math.floor(game.need*1.25+6)}game.effects.forEach(fx=>{fx.y-=.5*f;fx.life-=f});game.effects=game.effects.filter(fx=>fx.life>0);$('#stageText').textContent=`STAGE ${game.stage} ${game.kills}/${game.need}`;$('#runGold').textContent=game.gold;$('#hpFill').style.width=`${Math.max(0,p.hp/p.max*100)}%`;$('#xpFill').style.width=`${Math.min(100,game.xp/game.nextXp*100)}%`}
function drawIdle(){ctx.fillStyle='#050d19';ctx.fillRect(0,0,W,H)}
function draw(){ctx.fillStyle='#050d19';ctx.fillRect(0,0,W,H);ctx.fillStyle='#2a90a9';for(let i=0;i<70;i++){let y=(i*83+(game.time*.05)%83)%H;let x=(i*97)%W;ctx.fillRect(x,y,2,5)}let p=game.player;let src=`${p.ship.path}_lv${p.lv}.svg`;let im=loadImg(src);let shipSize=[78,88,104,120,140][p.lv-1]||98;ctx.drawImage(im,p.x-shipSize/2,p.y-shipSize/2,shipSize,shipSize);game.enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.kind==='bomber'?'#6a2b10':'#3b1720';ctx.strokeStyle=e.kind==='bomber'?'#ff9b2d':'#ff465c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,20);ctx.lineTo(-e.r,-e.r);ctx.lineTo(0,-4);ctx.lineTo(e.r,-e.r);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()});game.bullets.forEach(b=>{if(b.laser){ctx.globalAlpha=.45;ctx.strokeStyle=b.color;ctx.lineWidth=b.width;ctx.beginPath();ctx.moveTo(b.x,p.y-55);ctx.lineTo(b.x,0);ctx.stroke();ctx.globalAlpha=1}else{ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()}});game.effects.forEach(f=>{ctx.globalAlpha=Math.min(1,f.life/20);ctx.fillStyle=f.color;ctx.font='bold 16px Arial';ctx.fillText(f.t,f.x,f.y);ctx.globalAlpha=1})}
requestAnimationFrame(step);
