import {Assets} from './Assets.js';
import {Camera} from './Camera.js';
import {Input} from './Input.js';
import {Bullet} from '../entities/Bullet.js';
import {Player} from '../entities/Player.js';
import {WaveSystem} from '../systems/WaveSystem.js';
import {CollisionSystem} from '../systems/CollisionSystem.js';
import {ParticleSystem} from '../systems/ParticleSystem.js';
import {MetaSystem} from '../systems/MetaSystem.js';
import {HUD} from '../ui/HUD.js';
import {Menu} from '../ui/Menu.js';

export class Game{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.container=document.getElementById('game-container');this.world={width:canvas.width*2,height:canvas.height*2};this.camera=new Camera(canvas,this.world);this.input=new Input(canvas,this.camera);this.assets=new Assets();this.meta=new MetaSystem();this.player=new Player(this);this.wave=new WaveSystem(this);this.collision=new CollisionSystem(this);this.particles=new ParticleSystem();this.hud=new HUD(this);this.menu=new Menu(this);this.state='READY';this.last=0;this.resize();window.addEventListener('resize',()=>this.resize());}
  async boot(){await this.assets.load(this.assetList());this.resetRun();requestAnimationFrame(t=>this.loop(t));}
  assetList(){const p=[1,2,3,4,5].map(n=>({key:`player_lv${n}`,src:`assets/player/player_lv${n}.png`}));const e=['scout','fast','bomber','suicide','boss'].map(n=>({key:`enemy_${n}`,src:`assets/enemy/enemy_${n}.png`}));return [...p,...e];}
  resize(){this.canvas.width=this.container.clientWidth;this.canvas.height=this.container.clientHeight;this.world={width:this.canvas.width*2,height:this.canvas.height*2};this.camera.world=this.world;}
  resetRun(){this.stage=1;this.stageKills=0;this.killsRequired=15;this.goldEarned=0;this.skills={SK_M:1,SK_L:0,SK_C:0,SK_S:0,EV_M:0,EV_L:0};this.playerBullets=[];this.enemyBullets=[];this.enemies=[];this.chain=[];this.stars=Array.from({length:150},()=>({x:Math.random()*this.world.width,y:Math.random()*this.world.height,s:Math.random()*2+0.5,v:Math.random()*1.5+0.5}));this.player.reset();this.wave.reset();this.camera.follow(this.player);this.hud.update();}
  start(){this.menu.hideAll();this.resetRun();this.state='PLAY';}
  restart(){this.menu.hideAll();this.resetRun();this.state='PLAY';}
  gameOver(){if(this.state==='GAMEOVER')return;this.state='GAMEOVER';this.meta.data.gold+=this.goldEarned;if(this.stage>this.meta.data.bestStage)this.meta.data.bestStage=this.stage;this.meta.save();this.menu.showGameOver();}
  triggerLevelUp(){this.state='LEVEL_UP';const s=this.skills;const pool=[];if(s.SK_M===5&&s.SK_C>=1&&!s.EV_M)pool.push({id:'EV_M',name:'★진화★ 클러스터 미사일',desc:'미사일이 폭발 후 분열탄으로 확산됩니다.'});if(s.SK_L===5&&s.SK_M>=1&&!s.EV_L)pool.push({id:'EV_L',name:'★진화★ 프리즘 레이저',desc:'광폭 관통 레이저와 연쇄 전격을 발동합니다.'});if(s.SK_M<5&&!s.EV_M)pool.push({id:'SK_M',name:`미사일 Lv.${s.SK_M+1}`,desc:'기본 발사 수가 증가하고 기체 외형이 강화됩니다.'});if(s.SK_L<5&&!s.EV_L)pool.push({id:'SK_L',name:`레이저 Lv.${s.SK_L+1}`,desc:'전방 관통 레이저를 추가합니다.'});if(s.SK_C<5)pool.push({id:'SK_C',name:`체인 Lv.${s.SK_C+1}`,desc:'처치 시 주변 적에게 전격이 전이됩니다.'});if(s.SK_S<3)pool.push({id:'SK_S',name:`실드 Lv.${s.SK_S+1}`,desc:'기체 주변 실드가 적 탄환을 제거합니다.'});pool.push({id:'HEAL',name:'긴급 수리',desc:'내구도를 40% 회복합니다.'});this.menu.showLevel(pool.sort(()=>.5-Math.random()).slice(0,3));}
  selectSkill(id){if(id==='HEAL')this.player.hp=Math.min(this.player.maxHp,this.player.hp+this.player.maxHp*.4);else this.skills[id]++;this.menu.hideAll();this.state='PLAY';this.hud.update();}
  spawnMiniMissile(b,i){const ang=Math.PI/2+(i-1.5)*.45;this.playerBullets.push(new Bullet({x:b.x,y:b.y,type:'MISSILE',damage:b.damage*.4,vx:Math.cos(ang)*5,vy:-Math.sin(ang)*5,r:5}));}
  tryChain(e){if(this.skills.SK_C<=0)return;this.enemies.filter(o=>o!==e&&!o.dead&&Math.hypot(o.x-e.x,o.y-e.y)<230).slice(0,3).forEach(t=>{t.hp-=this.player.baseAtk*(.8+this.skills.SK_C*.25);this.chain.push({x1:e.x,y1:e.y,x2:t.x,y2:t.y,alpha:1,color:'#ff9f43'});});}
  update(dt,now){if(this.state!=='PLAY')return;this.player.update(dt,now);this.camera.follow(this.player);this.wave.update(now);this.stars.forEach(s=>{s.y+=s.v;if(s.y>this.world.height){s.y=0;s.x=Math.random()*this.world.width;}});this.playerBullets.forEach(b=>b.update());this.enemyBullets.forEach(b=>b.update());this.enemies.forEach(e=>e.update(now));this.collision.update();this.playerBullets=this.playerBullets.filter(b=>!b.dead&&b.y>-80);this.enemyBullets=this.enemyBullets.filter(b=>!b.dead&&b.y<this.world.height+80);this.enemies=this.enemies.filter(e=>!e.dead);this.chain.forEach(c=>c.alpha-=.08);this.chain=this.chain.filter(c=>c.alpha>0);this.particles.update();if(this.stageKills>=this.killsRequired){this.stage++;this.stageKills=0;this.killsRequired=Math.floor(this.killsRequired*1.28);this.wave.stageUp();}if(this.player.xp>=this.player.nextXp){this.player.xp-=this.player.nextXp;this.player.nextXp=Math.floor(this.player.nextXp*1.3);this.triggerLevelUp();}this.hud.update();}
  draw(){const c=this.ctx;c.clearRect(0,0,this.canvas.width,this.canvas.height);c.fillStyle='#06101f';c.fillRect(0,0,this.canvas.width,this.canvas.height);c.fillStyle='rgba(125,249,255,.7)';this.stars.forEach(s=>{const x=this.camera.screenX(s.x),y=this.camera.screenY(s.y);if(x>-10&&x<this.canvas.width+10&&y>-10&&y<this.canvas.height+10)c.fillRect(x,y,s.s,s.s*2.4);});c.strokeStyle='rgba(8,17,30,.9)';for(let x=-(this.camera.x%54);x<this.canvas.width;x+=54){c.beginPath();c.moveTo(x,0);c.lineTo(x,this.canvas.height);c.stroke();}for(let y=-(this.camera.y%70);y<this.canvas.height;y+=70){c.beginPath();c.moveTo(0,y);c.lineTo(this.canvas.width,y);c.stroke();}this.chain.forEach(cl=>{c.strokeStyle=`rgba(255,159,67,${cl.alpha})`;c.lineWidth=3;c.beginPath();c.moveTo(this.camera.screenX(cl.x1),this.camera.screenY(cl.y1));c.lineTo(this.camera.screenX((cl.x1+cl.x2)/2),this.camera.screenY((cl.y1+cl.y2)/2));c.lineTo(this.camera.screenX(cl.x2),this.camera.screenY(cl.y2));c.stroke();});this.playerBullets.forEach(b=>b.draw(c,this.camera));this.enemyBullets.forEach(b=>b.draw(c,this.camera));this.enemies.forEach(e=>e.draw(c,this.camera,this.assets));this.particles.draw(c,this.camera);this.player.draw(c,this.camera,this.assets);}
  loop(now){const dt=now-this.last;this.last=now;this.update(dt,now);this.draw();requestAnimationFrame(t=>this.loop(t));}
}
