const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');
const ui={score:document.getElementById('score'),best:document.getElementById('best'),level:document.getElementById('level'),hp:document.getElementById('hp'),startPanel:document.getElementById('startPanel'),gameOverPanel:document.getElementById('gameOverPanel'),finalScore:document.getElementById('finalScore'),startBtn:document.getElementById('startBtn'),restartBtn:document.getElementById('restartBtn')};
const W=canvas.width,H=canvas.height;let keys={},running=false,paused=false,frame=0,score=0,best=Number(localStorage.getItem('airplane1945_best')||0);let player,bullets,enemies,enemyBullets,items,particles,stars;ui.best.textContent=best;
function resetGame(){frame=0;score=0;running=true;paused=false;player={x:W/2,y:H-86,w:38,h:48,speed:4.2,hp:3,level:1,shotDelay:14,lastShot:0};bullets=[];enemies=[];enemyBullets=[];items=[];particles=[];stars=Array.from({length:70},()=>({x:Math.random()*W,y:Math.random()*H,s:Math.random()*2+.4,v:Math.random()*1.8+.4}));updateUI()}
function updateUI(){ui.score.textContent=score;ui.best.textContent=best;ui.level.textContent=player?player.level:1;ui.hp.textContent=player?player.hp:3}
function startGame(){ui.startPanel.classList.add('hidden');ui.gameOverPanel.classList.add('hidden');resetGame();requestAnimationFrame(loop)}
function gameOver(){running=false;if(score>best){best=score;localStorage.setItem('airplane1945_best',String(best))}ui.finalScore.textContent=`SCORE ${score}`;ui.gameOverPanel.classList.remove('hidden');updateUI()}
function drawPlayer(){const{x,y}=player;ctx.save();ctx.translate(x,y);ctx.fillStyle='rgba(0,0,0,.25)';ctx.beginPath();ctx.ellipse(0,18,28,12,0,0,Math.PI*2);ctx.fill();let g=ctx.createLinearGradient(-32,0,32,0);g.addColorStop(0,'#2c6bff');g.addColorStop(.5,'#9edcff');g.addColorStop(1,'#2c6bff');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,-26);ctx.lineTo(-34,18);ctx.lineTo(-9,10);ctx.lineTo(0,28);ctx.lineTo(9,10);ctx.lineTo(34,18);ctx.closePath();ctx.fill();ctx.fillStyle='#dce8ff';ctx.beginPath();ctx.moveTo(0,-34);ctx.lineTo(-11,24);ctx.lineTo(0,34);ctx.lineTo(11,24);ctx.closePath();ctx.fill();ctx.fillStyle='#112a55';ctx.beginPath();ctx.ellipse(0,-10,7,14,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ff8a24';ctx.beginPath();ctx.moveTo(-13,27);ctx.lineTo(-8,42);ctx.lineTo(-4,27);ctx.fill();ctx.beginPath();ctx.moveTo(13,27);ctx.lineTo(8,42);ctx.lineTo(4,27);ctx.fill();ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.type==='heavy'?'#7dff83':'#ff4a4a';ctx.beginPath();ctx.moveTo(0,24);ctx.lineTo(-24,-14);ctx.lineTo(-7,-5);ctx.lineTo(0,-24);ctx.lineTo(7,-5);ctx.lineTo(24,-14);ctx.closePath();ctx.fill();ctx.fillStyle='#222';ctx.beginPath();ctx.ellipse(0,2,7,12,0,0,Math.PI*2);ctx.fill();ctx.restore()}
function shoot(){if(frame-player.lastShot<player.shotDelay)return;player.lastShot=frame;const patterns=[[0],[-7,7],[-12,0,12],[-16,-5,5,16],[-22,-10,0,10,22]];patterns[Math.min(player.level,5)-1].forEach(dx=>bullets.push({x:player.x+dx,y:player.y-32,vx:dx*.025,vy:-8,r:4,dmg:1}))}
function spawnEnemy(){const heavy=Math.random()<.18+Math.min(score/8000,.12);enemies.push({x:32+Math.random()*(W-64),y:-40,w:heavy?46:36,h:heavy?52:42,hp:heavy?4:2,type:heavy?'heavy':'normal',speed:heavy?1.35:2+Math.min(score/7000,1.2),shootTick:frame+Math.floor(Math.random()*80)+60})}
function spawnItem(x,y){const r=Math.random();items.push({x,y,type:r<.48?'power':r<.82?'speed':'heal',r:12,vy:2})}
function hit(a,b,p=0){return a.x<b.x+b.w/2+p&&a.x>b.x-b.w/2-p&&a.y<b.y+b.h/2+p&&a.y>b.y-b.h/2-p}
function explode(x,y,color='#ffdf3d'){for(let i=0;i<14;i++){const a=Math.random()*Math.PI*2,s=Math.random()*3+1;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:28,color})}}
function update(){frame++;stars.forEach(s=>{s.y+=s.v;if(s.y>H){s.y=-5;s.x=Math.random()*W}});if(keys.ArrowLeft||keys.a||keys.A)player.x-=player.speed;if(keys.ArrowRight||keys.d||keys.D)player.x+=player.speed;if(keys.ArrowUp||keys.w||keys.W)player.y-=player.speed;if(keys.ArrowDown||keys.s||keys.S)player.y+=player.speed;player.x=Math.max(28,Math.min(W-28,player.x));player.y=Math.max(40,Math.min(H-40,player.y));if(keys[' ']||keys.Spacebar)shoot();const interval=Math.max(28,70-Math.floor(score/350));if(frame%interval===0)spawnEnemy();bullets.forEach(b=>{b.x+=b.vx;b.y+=b.vy});bullets=bullets.filter(b=>b.y>-20);enemies.forEach(e=>{e.y+=e.speed;if(frame>e.shootTick&&e.y>40){enemyBullets.push({x:e.x,y:e.y+22,vy:3.6,r:5});e.shootTick=frame+90+Math.floor(Math.random()*70)}});enemyBullets.forEach(b=>b.y+=b.vy);enemyBullets=enemyBullets.filter(b=>b.y<H+20);items.forEach(it=>it.y+=it.vy);items=items.filter(it=>it.y<H+30);bullets.forEach(b=>enemies.forEach(e=>{if(!b.dead&&hit(b,e,b.r)){b.dead=true;e.hp-=b.dmg;explode(b.x,b.y,'#7df9ff')}}));bullets=bullets.filter(b=>!b.dead);enemies.forEach(e=>{if(e.hp<=0&&!e.dead){e.dead=true;score+=e.type==='heavy'?200:100;explode(e.x,e.y,e.type==='heavy'?'#7dff83':'#ff4a4a');if(Math.random()<.22)spawnItem(e.x,e.y)}});enemies=enemies.filter(e=>!e.dead&&e.y<H+60);enemies.forEach(e=>{if(Math.abs(e.x-player.x)<(e.w+player.w)/2-8&&Math.abs(e.y-player.y)<(e.h+player.h)/2-8){e.dead=true;player.hp--;explode(player.x,player.y,'#ff8a24')}});enemyBullets.forEach(b=>{if(!b.dead&&Math.hypot(b.x-player.x,b.y-player.y)<20){b.dead=true;player.hp--;explode(player.x,player.y,'#ff8a24')}});enemyBullets=enemyBullets.filter(b=>!b.dead);items.forEach(it=>{if(!it.dead&&Math.hypot(it.x-player.x,it.y-player.y)<30){it.dead=true;if(it.type==='power')player.level=Math.min(5,player.level+1);if(it.type==='speed')player.shotDelay=Math.max(6,player.shotDelay-2);if(it.type==='heal')player.hp=Math.min(5,player.hp+1);explode(it.x,it.y,it.type==='heal'?'#7dff83':'#ffdf3d')}});items=items.filter(it=>!it.dead);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.life--});particles=particles.filter(p=>p.life>0);if(player.hp<=0)gameOver();updateUI()}
function drawBackground(){ctx.fillStyle='#07101f';ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(125,249,255,.75)';stars.forEach(s=>ctx.fillRect(s.x,s.y,s.s,s.s*2.4));ctx.strokeStyle='rgba(46,252,255,.12)';ctx.lineWidth=1;for(let y=frame*2%60;y<H;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function draw(){drawBackground();bullets.forEach(b=>{ctx.fillStyle='#55b7ff';ctx.beginPath();ctx.ellipse(b.x,b.y,4,12,0,0,Math.PI*2);ctx.fill()});enemyBullets.forEach(b=>{ctx.fillStyle='#ff9b2f';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill()});items.forEach(it=>{ctx.fillStyle=it.type==='power'?'#55b7ff':it.type==='speed'?'#ffdf3d':'#7dff83';ctx.beginPath();ctx.arc(it.x,it.y,it.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#06101f';ctx.font='bold 12px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(it.type==='power'?'P':it.type==='speed'?'S':'+',it.x,it.y+1)});enemies.forEach(drawEnemy);drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(p.life/28,0);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1})}
function loop(){if(!running)return;if(!paused){update();draw()}requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='p'||e.key==='P')paused=!paused;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});window.addEventListener('keyup',e=>keys[e.key]=false);ui.startBtn.addEventListener('click',startGame);ui.restartBtn.addEventListener('click',startGame);
player={x:W/2,y:H-86,w:38,h:48,hp:3,level:1};bullets=[];enemies=[];enemyBullets=[];items=[];particles=[];stars=Array.from({length:70},()=>({x:Math.random()*W,y:Math.random()*H,s:Math.random()*2+.4,v:Math.random()*1.2+.3}));drawBackground();drawPlayer();
